### ISSUE TITLE
Try to keep F10 menus consistent between helos

### ISSUE THREAD

**Issue by ddunwoody** [ModernColdWar/RedStormRising#114]
For use with macro programs - even if commands are highly nested!

**Comment by madrabbit711** [comment]
This seems to be working nicely with the recent changes.  Close it?

**Comment by madrabbit711** [comment]
These post-birth added options don't work sometimes, even in SP.  
https://github.com/ModernColdWar/RedStormRising/blob/f1100abd394ebafea0c152deb32b7dcf07af47bf/birthEventHandler.lua#L70-L99

Menu also more cluttered now.  Consider reformatting additions in CTLD.lua themselves to allow for more uniform menu.

**Comment by madrabbit711** [comment]
Temp solution:
Use "F10. Other > F5. Cargo Menu" first

**Comment by madrabbit711** [comment]
- disabled CTLD radio menu shortcuts copied and added by birth eventHandler to diagnose intermittent problems with logistics
https://github.com/ModernColdWar/RedStormRising/blob/5215ab6345aaa8b579b2d916e09db28ad53392d9/birthEventHandler.lua#L80-L81
