### ISSUE TITLE
Add JTAC behaviour to JTACs that are part of base defences

### ISSUE THREAD

**Issue by Winston2108** [ModernColdWar/RedStormRising#120]
Currently we only add JTAC behaviour to CTLD-sourced units; these units have been added to base defences so we need to move the "add CTLD JTAC behaviour" call to the point where we *either* unpack, reload from disk *or* activate from base defence units.

**Comment by madrabbit711** [comment]
CTLD.lua line 2439:
`                    if ctld.isJTACUnitType(_crate.details.unit) and ctld.JTAC_dropEnabled then
                        local _code = ctld.getLaserCode(_heli:getCoalition())
                        ctld.JTACAutoLase(_spawnedGroups:getName(), _code)
                    end`

**Comment by madrabbit711** [comment]
https://github.com/ModernColdWar/RedStormRising/blob/21455c0f6805ef54efc401ee9eab704747563132/persistence.lua#L89-L99

Similar issues in bases.lua fixed in upcoming commit.
