### ISSUE TITLE
Improve base capture - (2) Change FOB (and base?) campaign init to set baseOwner from Trigger Zone color

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#125]
**Part of larger Improve base capture radius checks change #123**

Base ownership is determined in 3 different scenarios:
a) Campaign init
b) Server restart - map unit persistence
c) Base capture

**Problem**
Base owner should be determined by current defenders but need to be able to set base owner prior to spawning these defenders for (a) campaign start and (b) server restart

**Implementation:**

Segregate base ownership from occupying units
1a. Need table of all bases and FOBs in RSR_config.lua to allow setting of ownership for (a) Campaign start that is utilised if no persistence JSON present
1b. Make table of all bases and FOBs in RSR_config.lua that can respected during normal campaign run in-case of emergency?
2. Need 'last ownership' table of all bases and FOBs that is exported pre-server restart with persistence.lua 
3. Associate (b) server restart persistence with last ownership table

**Comment by madrabbit711** [comment]
Already in rsrState.json:

`{
  "baseOwnership": {
    "airbases": {
      "blue": [ "Sukhumi-Babushara", "Vaziani", "Batumi", "Gudauta", "Soganlug", "Tbilisi-Lochini", "Senaki-Kolkhi", "Kobuleti" ],
      "neutral": [],
      "red": [ "Novorossiysk", "Krasnodar-Pashkovsky", "Maykop-Khanskaya", "Sochi-Adler", "Kutaisi", "Anapa-Vityazevo", "Mozdok", "Gelendzhik", "Mineralnye Vody", "Nalchik", "Krasnodar-Center", "Krymsk", "Beslan" ]
    },
    "farps": {
      "blue": [ "BlueStagingPoint", "LN16", "MN61", "LM56", "LN90", "MM75", "KN70", "MM69", "LN21", "KN76", "GG19", "GH03", "LM95", "GH17", "KN53", "MM25", "RedBeachhead" ],
      "neutral": [],
      "red": [ "LP17", "EJ08", "FJ53", "GJ38", "BlueBeachhead", "FJ03", "EK51", "EK20", "FJ69", "MP24", "EK14", "DK65", "FJ95", "EJ98", "GJ22", "RedStagingPoint", "LP31", "DK61", "EJ34", "LP65", "MN12", "MN19", "KP74", "MN34" ]
    }
  },`

**Comment by madrabbit711** [comment]
This task is unnecessary.  Persistance.lua already looks for rsrState.json file and if present, reads the base and FOB ownership as saved during the campaign and before restarts.

Closing.

**Comment by madrabbit711** [comment]
Discussion from Discord:
Easier to setup campaign base ownership with Trigger Zone name change = map overview + right click Trigger Zone List in mission editor to zoom to FOB
e.g. "MM75 Blue"

FOB ownership set by trigger zone name.
Base ownership determined by warehouse coalition setting (as it is already).

**Comment by madrabbit711** [comment]
Makes no sense mechanistically for attackers to be able to take over a FOB and utilise existing (enemy?) logistic centre.  Also better for logistic centre locations to be pre-determined but randomly selected for FOBs (and bases) = FOB crate unpack = repair c.f. build logistic centre on unpacked spot spot.

**Therefore PLAN B**

Also easier to have side associated "outpost" structure pre-placed in mission editor **within 2km of FARP helipad**  + FARP trucks on late activation
-  side associated "outpost" determines side of neutral FARP helipad in absence of late activation FARP trucks from both sides 
-  determines campaign init and restart side association for FOBs
-  requires no further coding other than editing MIZ to pre-place outposts within 1 of pre-determined logistic centre locations

Another benefit is that MIZ setup is easier for start of campaign:
- base warehouse determines base side association, but still allows base logistics centre to be neutral and thus "loyal to current base owner"
- outpost side assoc determines FOB side association if within 2km of FARP helipad
Both of these are easy to setup with drop-down menus.

**COMPARISON**

PLAN A - Trigger Zone Name = determines FOB init side
- more annoying MIZ setup = bad
- does not require pre-placed side assoc. outpost  = good
- outpost not required to be within 2km = good
- outpost can be neutral and should not show on map = good

PLAN B  - Side Assoc. Outpost = determine FOB init side
- easier MIZ setup = good
- requires pre-placed side assoc. outpost  = fine for init, bad for rest of campaign unless we mess with late activation flag for static object?!
- outpost required to be within 2km = bad due to limited areas around some FOBs
- outpost cannot be neutral and will show on map = bad

**Implementation:**
- Intercept here:
https://github.com/ModernColdWar/RedStormRising/blob/5954de0a1309fc4906d2bf36d348058858f449ab/queryDcs.lua#L21-L22

- Need to figure out deletion of static objects within DCS regardless of whether PLAN A or PLAN B to allow logistics centre randomization and messing with persistence etc.


Of concern:
https://github.com/ModernColdWar/RedStormRising/blob/5954de0a1309fc4906d2bf36d348058858f449ab/CTLD_config.lua#L25

https://wiki.hoggitworld.com/view/DCS_func_destroy
"Due to a bug, this function does not currently work on scenery objects (dcs 1.2.14)"
But does it work on dynamically or mission editor placed static objects?  Currently utilised by CTLD.lua for crate destruction.

**Comment by Winston2108** [comment]
Just a quick couple of fast comments while I think about "Plan B":

* The `destroy` function works for crates in single-player, but not in multiplayer (which is why the crates hang around, sometimes literally!). You can set an explosion to destroy a static, but that's pretty nasty.
* On randomisation of location, we can do "random point in zone" easily in MOOSE, but that can put the logistics in odd places.  We could also (this idea from deebix) place multiple trigger zones and pick one of them randomly in the code.

**Comment by madrabbit711** [comment]
https://github.com/ModernColdWar/RedStormRising/blob/5954de0a1309fc4906d2bf36d348058858f449ab/CTLD.lua#L953

Is a static object assigned a country but only associated with a coalition with:
coalition.addStaticObject

Thus can we dynamically change the ownership of a static building by simply reassigning it to a coalition?

This would allow the easier MIZ setup of placing a side assoc. CC just for the campaign init FOB side assignment, but then setting it's coalition, even as neutral, dynamically as needed post spawn and for the rest of the campaign.

**Comment by madrabbit711** [comment]
> * On randomisation of location, we can do "random point in zone" easily in MOOSE, but that can put the logistics in odd places.  We could also (this idea from deebix) place multiple trigger zones and pick one of them randomly in the code.

Yes the multiple trigger zones then select one randomly would be my preference as well as I stated above with:
"better for logistic centre locations to be pre-determined but randomly selected for FOBs (and bases)"

> * Late activation for statics: I believe this either doesn't exist or doesn't work, which is why we don't do it, but not 100% sure on that as not at my DCS PC to test.

Also seems to uncertain an approach and adds to 'total objects on map performance problems'.

**Comment by madrabbit711** [comment]
Initial implementation completed:

https://github.com/ModernColdWar/RedStormRising/blob/459c898533729979e9cb1a557817d28629ff39e1/queryDcs.lua#L62-L93

**Comment by madrabbit711** [comment]
Closing this task as it works for campaign init of FOBs.  

Airbase coalition can already determined by warehouse coalition in the absence of any ground units or side assoc. static objects.  Therefore this campaign init method should not be needed for airbases.
