### ISSUE TITLE
"Fix" "airquake"

### ISSUE THREAD

**Issue by Winston2108** [ModernColdWar/RedStormRising#129]
# Oveview

When player numbers are higher, there is a (minority?/majority?) view that the server can degenerate into "air-quake" with high sortie rates and rapid deaths by some players.

# Fixes (agreed)

There are some current features/limitations that certainly contribute to this, which unambiguously we should fix.  These are:

1) Award of full complement of life points upon joining, regardless of progress through the mission
2) "Too high" base number of lives because of the need to be generous in case you're on the outnumbered side.

Fixing (1) and (2) would allow us to lower the base number of lives; this would help tremendously already, and fixing this is the aim of issue #95.

# Further "fixes" (not agreed)

There are further things we *could* do, and should discuss as part of this issue.  We can't do all of these, as some of them conflict, but options include:

1) Only allowing "advanced"/capable aircraft from a subset of bases, for example the corner airfields.  This reduces the effectiveness of airquake as only the "crap" aircraft are available at most bases, but doesn't eliminate it at the corners.  This could be done purely in the mission editor, or dynamically in the code.
1) Making more advanced aircraft more expensive
1) Rate limiting aircraft per airfield; for example even if you have lots of lives (heavily outnumbered), you can only take off so many times from a given airfield in a given airframe.
1) Splitting life points per aircraft (BlueFlag-style; 2 CAP lives, 4 intercept lives etc)

**Comment by Winston2108** [comment]
My thoughts:

I'm planning to do the fixes that are agreed as part of #95, and I don't think we should discuss those here.  If we wanted to turn that off, we'd just cap the min and max ratios for scaling at 1.

On the "further fixes", my thoughts are:

On 1: I think there is some merit in this, but I don't personally like it.  I think if it were done it would need to be done statically in the ME, as otherwise it's difficult and confusing.  Perhaps the good idea that comes out of this would be removing a few fields from spawning A/C, a la DDCS.  On there, I think these fields are Novo, Guduata, Kutaisi,  and one of the Krasnadors.

On 2: I like this idea, but it's hard to say that something is twice as good as something else, so I'd prefer 4.

On 3: This is my preferred solution.  If you keep doing the same thing *and dying quickly*, we stop you from doing it for a while.  So you take an 18 out of Senaki, and get killed as you take off.  You can do the same again 5 minutes later, but then you're out of luck and have to fall back to Batumi (or wherever), or try again in an F-5.  You could tie this to the airframe type pools (you get two attempts in a CAP aicraft, then 2 in an interceptor, *per base*, *per hour* [or whatever]).

On 4: Better than 2, but I'd fold it into 3.

**Comment by Winston2108** [comment]
From Mobius on Discord:

> @Winston about the rate limiting depending on players, instead of simply increasing the total number of airframes if the player is outnumbered, I would suggest we institute 2 systems for resupply that work side by side:

> 1.  A system that automatically resupplies an airfield with planes based on time
> 2.  A system that resupplies an airfield based on player actions, like transporting supplies from a nearby FARP or airfield. 

> I’m the case of a player being really outnumbered, the time in between resupplies for #1 could be reduced based on player ratio for the outnumbered team and increased based on that ratio for the outnumbering team.

> We could also do a compromise between both parties (those who do not want any advanced planes at forward bases and those who do) and designate forward airbases as having some advanced planes, but not nearly as many as the rear bases.

> **there would always be a hard limit however. For example, there could never be more than ### of F-16’s at a certain base (frontlines being significantly less than rear bases).

**Comment by chandawg** [comment]
this seems to be resolved with a combination of things, changing to Syria for a map, having dedicated bases CAP/Multirole/CAS, lives, and weapon restrictions.
