### ISSUE TITLE
Improve base capture - (6) Review logistics aircraft: types and plane crate pickup from ramp

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#131]
A) Review current logistics aircraft i.e. those allowed to take internal crates.

https://github.com/ModernColdWar/RedStormRising/blob/5954de0a1309fc4906d2bf36d348058858f449ab/CTLD_config.lua#L272-L282

B) Allow planes to take crate from ramp without need to go to CC.

**Comment by MobiSev** [comment]
WW2 planes that are currently in the server: 
- both Spitfires
- FW-190A8
- FW-190D9
- both P-51's
- I-16

**Comment by madrabbit711** [comment]
Test currently disabled functionality:
https://github.com/ModernColdWar/RedStormRising/blob/3bb91b4518ff8f7405bef7b76f40887302962846/CTLD.lua#L4353

**Comment by madrabbit711** [comment]
Added WWII planes. Needs testing with co-introduced 'load from ramp' capabilities in CTLD.lua.
https://github.com/ModernColdWar/RedStormRising/blob/9b47b3d322854227000d618b6c23851a7299b64b/CTLD_config.lua#L238-L297
