### ISSUE TITLE
Revert ammo trucks to low res version to allow FARP rearm

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#132]
High resolution ammo trucks newly added as slingable to RSR will not allow rearm from FARP helipads.  Definitely for blue (confirmed by myself and Mobius), unsure about red.

This is game breaking as players will not be able to rearm from captured FARPs.

Unsure where/how this change was introduced as current master repo still correct i.e. using old trucks:
https://github.com/ModernColdWar/RedStormRising/blob/5954de0a1309fc4906d2bf36d348058858f449ab/CTLD_config.lua#L417-L422

**From Discord:**

Whilst doing some diving into the FARP helipads I came across:
`DCS World OpenBeta\Scripts\Database\FARP.lua`

In it, it seems to state the only vehicles that can allow rearm/refuel for red/blue.  These being:

red
`[RESOURCE_AMMO] = { "URAL_4320_B", "SetkaKP" },
fuel_units_red = { "URAL_ATZ-10", "ATZ-10", "ATZ-60", "GSM Rus" }
URAL_4320_B = Ural 375`

blue
`[RESOURCE_AMMO] = { "M-818" },
fuel_units_blue = { "HEMTT", "GSM Rus"  }`

====
I did not see the newly introduced blue assoc. `KrAZ-6322` anywhere.  My own testing in the mission editor also seems to suggest this will not allow blue helos to rearm at the FARP helipad.

Weirdly the 'KAMAZ-43101' is not in the above list either.  But my own testing seems to suggest it works fine.  I wonder if this is because in:
`\DCS World OpenBeta\Scripts\Database\vehicles\unarmed\KAMAZ-43101 truck.lua`
it seems to inherit the shape `KAMAZ-TENT`, which is in the above` FARP.lua` under `[RESOURCE_GROUND_SERVICE]`.

**Comment by Winston2108** [comment]
Fixed in 49678a4ffc5cc27bee8f31ae1053df1977e376cc; will take effect at 0500Z tonight (!)
