### ISSUE TITLE
Update `SimpleSlotBlockGameGUI.lua` to differentiate Game Master from TacCom

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#160]
"instructor" = Game Master
"artillery_commander" = TacCom
"forward_observer" = JTAC/GCI

**Comment by Winston2108** [comment]
Aha!  I don't know how I missed that; thank you.

**Comment by madrabbit711** [comment]
Completed by Winston:
https://github.com/ModernColdWar/RedStormRising/blob/7eaf19e1f530815974264a079ae90d43158b0898/Hooks/RSRSlotBlocker.lua#L10-L21
