### ISSUE TITLE
Prevent or allow Mi8 and Huey to take troops and internal crate simultaneously?

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#163]
Related to #141 

Currently in RSR 4.0:
- can load troops and logistics crate in any order 
OR 
- troops then JTAC crate but NOT JTAC crate then troops

Current intent of code is to only allow either troops or crate, not both.

However (from Discord discussion):
"There should be some way for poor Huey and Mi8 pilots to defence themselves i.e. carry MANPAD group, whilst doing crucial repair/JTAC deployment missions for the team, with the only advantage these helos at the moment is 'cargo space'."

Needs further feedback from team.

**Comment by Winston2108** [comment]
You make an excellent point on the need for a manpad, and so I've rethought my position to be that you can take a manpad group with a crate, but not any other type.  As a developer-time-saving measure I'd be content with allowing troops and crates for now (obviously in any order!).

I was tempted to say the Mi8 should be able to take both troops and a crate, and the Huey only one or the other, but I think for gameplay it's important that they have the same capabilities, internal cargo wise.

**Comment by madrabbit711** [comment]
can be disallowed with ctld.simultaneousTroopInternalCrateLoad
https://github.com/ModernColdWar/RedStormRising/blob/master/CTLD.lua#L2157-L2162
https://github.com/ModernColdWar/RedStormRising/blob/1d5e9ca8bd0a6a673da2d40c6fcfc2ea2dcab20f/CTLD.lua#L2558-L2563
