### ISSUE TITLE
Save state of base defences between restarts

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#169]
In the absence of a resupply system, base defences are late activated groups.  Thus half destroyed base defences post restart may require only those groups to be activated post restart.
e.g. Groups 1 to 8 of 20 across restart.

...however this leads to a weird scenario where-in if a base is taken by enemy then recaptured, the recapturing team will only get the half of base defences that weren't activated post-restart?!
e.g. Groups 9 to 20 on recapture.

Unsure if this worth the work...

https://github.com/ModernColdWar/RedStormRising/blob/master/bases.lua#L24-L46

**Comment by chandawg** [comment]
using Moose warehouses, the status of resupply forces is saved for restart
