### ISSUE TITLE
Improve base capture -  (4) Change logistics centre buildings

### ISSUE THREAD

**Issue by ddunwoody** [ModernColdWar/RedStormRising#17]

**Comment by madrabbit711** [comment]
Note from public Discord discussion:
- CC separated from capture (not side associated)
> Allows us to also think about expansion to other building types as well if their not capture assoc. commms tower for resupply and base alert, barracks for pilots, etc.
- CC at Bases and possibly FOBs = bunker type
> difficult to kill
- CC at deployable FOBs = tent
> easy to kill, camouflaged better (makes sense also helo transported as well)

**Comment by madrabbit711** [comment]
Need to determine if tent is to easy to destroy e.g. clipped by helo, therefore effecting gameplay.

**Comment by madrabbit711** [comment]
Need to determine if tent object suggested for deployable FOBs is "too" susceptible damage e.g. helo bump, rotor clip, damage by swinging crate, etc and therefore unsuitable.

**Comment by madrabbit711** [comment]
TESTING:
- "FARP Tent" object far more susceptible to damage.  Helo landing on tent will collapse it (as expected) = too susceptible to griefing, arguments, frustration, etc.
- "Helipad Single" useful.  Rearm trucks are not required to be on pad.  However player is required to be on pad.  Pad needs to be within 200m radius of ammo/fuel truck.

Suggested changes:
- "Command Center" building for air bases = difficult to kill
- "Outpost" building for FOBs = easy to kill (+ remove co-spawned "Watchtower" building)
- "Outpost" or "FARP Tent" for deployable FOBs = FARPs 
- Allow "Helipad Single" as slingable asset

**Comment by Winston2108** [comment]
I like the idea of airbases having a command center building that has to be hit with a "big bomb" vs the FARPs being much more squishy.

I'm surprised that "Helipad single" is dynamically spawnable - does it really work if added in dynamically?

**Comment by madrabbit711** [comment]
All bases (airbase/FOB) logistics centres = 'bunker' for now.
Still need to differentiate deployable FARPs from base repair to then build 'tent' instead.

**Comment by madrabbit711** [comment]
https://github.com/ModernColdWar/RedStormRising/blob/0f2b354af786dc70e1890b05b63f46f49e4873fe/CTLD.lua#L977-L982
