### ISSUE TITLE
Use MOOSE to keep AWACs airborne

### ISSUE THREAD

**Issue by ddunwoody** [ModernColdWar/RedStormRising#25]
Replace triggers we currently have so we always have AWACs on station.

Possible code (from examples [here](https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/master/SPA%20-%20Spawning)):InitRepeatOnEngineShutDown

```lua
SPAWN:New("AWACS group name"):InitLimit(1, 0):InitRepeatOnLanding(60, 0):InitCleanUp(300):SpawnScheduled(60, 0)
```

**Comment by Winston2108** [comment]
Done by @chandawg (thank you!)
