### ISSUE TITLE
Persist slung FOBs

### ISSUE THREAD

**Issue by ddunwoody** [ModernColdWar/RedStormRising#5]
Save/reload the logistics buildings unpacked using FOB crates.

Call `ctld.spawnFOB` as per `spawnLogisticsBuildingForBase`, but also remember to call `table.insert(ctld.logisticUnits, _fob:getName())` and `table.insert(ctld.builtFOBS, _fob:getName())` if `ctld.troopPickupAtFOB == true` (this from the body of `ctld.unpackFOBCrates`).

**Comment by Winston2108** [comment]
Won't do.

**Comment by chandawg** [comment]
I agreed with having the FOB not persist across restarts but now that we are restarting every 4 hours I think it could be argued that they should be Persistent

**Comment by Winston2108** [comment]
I'd come back at you to get Sky to increase the restart interval again!

This is one of the reasons I want to do #52 and #31 as that would decouple at least the base repair mechanic from the restart time.

I'm also slightly reluctant to look at this until I stop hearing occasionally that the "FOBs don't work", which may well involve actually finding the underlying problem.

**Comment by chandawg** [comment]
The restart time can't be extended past 5 hours due to either a loop in the ctld/lua code or a memory leak in DCS, but can't be determined.
