### ISSUE TITLE
SAM repair crates don't work

### ISSUE THREAD

**Issue by chandawg** [ModernColdWar/RedStormRising#59]
When a repair crate is slung for Hawk SAM the message "Cannot repair HQ-7 SAM System. No damaged HQ-7 SAM System with 100m."

**Comment by chandawg** [comment]
label: bug

**Comment by Winston2108** [comment]
No complaints lately?  Fixed @chandawg ?

**Comment by chandawg** [comment]
It worked, once didn't work the next time though. Next time I get on will test, if it doesn't work I will reopen the issue

**Comment by MobiSev** [comment]
test

**Comment by chandawg** [comment]
I received an email with "test" but didn't see a test somment5

**Comment by Winston2108** [comment]
Confirmed recently - got a message saying "No ROLAND system" when trying to repair a Buk.  Will look through the code and either change it to allow any SAM system to be repaired, or add type-specific repairs if that's difficult.

No ETA; will come after resupply and CSAR at least.

**Comment by Winston2108** [comment]
Should be fixed now - actually easy enough in the end, and I'm focussing on bug fixes now before adding more stuff that might be broken.  I appreciate that's not really the DCS/Eagle Dynamics way, but 🤷‍♂
