### ISSUE TITLE
Check CSAR life point slot blocking is working

### ISSUE THREAD

**Issue by ddunwoody** [ModernColdWar/RedStormRising#61]
Check that the CSAR script is appropriately blocking slots (it's currently erroring out)

**Comment by Winston2108** [comment]
The _takeoff_ and _land_ events do appear to be fine for this.  Next step is to enumerate the payload for these to deduct the appropriate cost.

**Comment by Winston2108** [comment]
It doesn't block slots - it blows up the aircraft above a certain height.
