### ISSUE TITLE
Blue EWR not broadcasting

### ISSUE THREAD

**Issue by madrabbit711** [ModernColdWar/RedStormRising#99]
Blue EWR still not broadcasting to blue players despite recent fix by Winston to ensure blue EWR set to freq. 124:
https://github.com/ModernColdWar/RedStormRising/commit/ca92e6e442964447705cd71af77e487c3a347219

As discussed, most likely related to long standing issue with EWR country and subsequent coalition association:
https://forums.eagle.ru/showthread.php?t=130723&page=4

Current "hasNumericCallsign" in "DCS World OpenBeta\Sounds\Speech\common.lua":
`
	return 	country == base.country.RUSSIA or
			country == base.country.UKRAINE or
			country == base.country.BELARUS or
			country == base.country.INSURGENTS or
			country == base.country.ABKHAZIA or
			country == base.country.SOUTH_OSETIA or
			country == base.country.CHINA or
			country == base.country.VIETNAM or 
			country == base.country.USSR or
			country == base.country.YUGOSLAVIA or
			(country == base.country.id.USA and forcesName == 'NAVY')	-- TODO: Make correct Numeric Callsign for US NAVY
`

Seems like ED trying to fix issue by adding "NAVY" as a country.  Need to investigate country and coalition assigned for EWR when spawned.

**Comment by madrabbit711** [comment]
RSR v3.4.1:

RED coalition:
Abkhazia, Belarus, Brazil, China, Iran, Kazakhstan, North Korea, Pakistan, Russia, Serbia, South Ossetia, Syria, USAF Aggressors, Yugoslavia

BLUE coalition:
Australia, Belgium, Canada, Croatia, Czech Republic, Denmark, France, Georgia, Germany, Israel, Italy, Norway, Poland, South Korea, Spain, Sweden, The Netherlands, Turkey, UK, **Ukraine**, USA, **USSR**

Matching this list to the above, the EWR needs to be from Ukraine or USSR.

**Comment by madrabbit711** [comment]
Following snippets from CTLD.lua indicate country for spawned group and associated crate (crates have a country?!) is derived from player country.  As all helos on blue are set to USA, all EWRs will be USA.

`function ctld.spawnCrateStatic(_heli:getCountry(), _unitId, _point, _name, _crateType.weight, _side, _internal)`

`local _details = { units = _troops, groupId = _groupId, groupName = string.format("Dropped Group %i", _groupId), side = _side, country = _country }`

`_group.country = _heli:getCountry()`

This creates a conflict, as the EWR is not available from the USA = EWRs not broadcasting.  However from testing a Ukraine EWR will broadcast to a USA plane.  I have only tested this 

**Solutions:**
Possible quick solution is to change all blue helos from USA to Ukraine or USSR.  This will in-turn ensure that all spawned EWRs are derived from the new player country of Ukraine and thus will broadcast.

_Need to ask Quaggles for tool he made to quick change aircraft parameters in a MIZ file_

**Potential problems:**
All other ground vehicles will be from Ukraine.  Does this affect their engagement?  Will need to test.

**Comment by Winston2108** [comment]
Should be fixed in cef83944e1079ca2433f32531260dc21560a71ab, which makes blue EWRs Ukrainian as a special case during unpacking's spawn in CTLD.

This should be preserved fine after a restart as `state.getGroupData` fetches and persists the country.

Will test tonight.
